import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Hero from "@/components/Hero";
import About from "@/components/About";
import { ClerkProvider } from "@clerk/nextjs";
import HowItWorks from "@/components/Howitworks";
import Faq from "@/components/Faq";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <div className="mt-2">
          <Navigation />
          <Hero />
        </div>
        <About />
        <HowItWorks />
        <Faq />
        <Footer />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
